[package]
name = "cobapi"
version = "0.5.0"
edition = "2021"

[dependencies]
cobapi-macros = { path = "../cobapi-macros" }
engage-il2cpp = { git = "https://github.com/DivineDragonFanClub/engage-il2cpp", default-features = false, features = [
    "app-eventscript",
    "app-procinst",
    "root-configbasicmenuitem",
    "system-collections-generic-dictionary_2",
    "system-collections-generic-list_1",
    "system-object",
] }
