[package]
name = "cobapi"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/DivineDragonFanClub/cobapi"
description = "Plugin API for the Cobalt mod loader"

[dependencies]
cobapi-macros = { version = "0.1.0", path = "cobapi-macros" }
thiserror = "1"
unity-nx = { git = "https://github.com/DivineDragonFanClub/unity-nx", tag = "0.1.0" }
engage-il2cpp = { git = "https://github.com/DivineDragonFanClub/engage-il2cpp", tag = "0.1.0", default-features = false, features = [
    "app-eventscript",
    "app-procinst",
    "root-configbasicmenuitem",
    "system-collections-generic-dictionary_2",
    "system-collections-generic-list_1",
    "system-object",
] }
